In [1]:
import numpy as np

In [3]:
#one of the real example of randint
while True:
    otp1 = np.random.randint(1000,10000,1)
    print("your otp is -" , otp1)
    user_otp = int(input('enter otp'))
    if otp1 == user_otp:
        print('successfully logged in')
        break
    else:
        print('invalid otp')
        continue

your otp is - [6603]
enter otp6578
invalid otp
your otp is - [7307]
enter otp7307
successfully logged in


# SORTING

In [4]:
# to short np.random.ranint
from numpy.random import randint as ri

In [6]:
m = ri(1,100,25).reshape(5,5)  #matrix of random integer

print("\n5*5 matrix of random integers\n" , '-'*50,"\n", m)

print("\n here is sorted matrix along row\n",'-'*50,"\n",np.sort(m))  #by default axis = 1


print("\n here is the sorted matrix along column\n",'-'*50,"\n" , np.sort(m , axis = 0))


5*5 matrix of random integers
 -------------------------------------------------- 
 [[82 68 77 47 95]
 [22 15  9 12 68]
 [55 77 90 99 93]
 [88 74 35 46 92]
 [49 91 95 58 99]]

 here is sorted matrix along row
 -------------------------------------------------- 
 [[47 68 77 82 95]
 [ 9 12 15 22 68]
 [55 77 90 93 99]
 [35 46 74 88 92]
 [49 58 91 95 99]]

 here is the sorted matrix along column
 -------------------------------------------------- 
 [[22 15  9 12 68]
 [49 68 35 46 92]
 [55 74 77 47 93]
 [82 77 90 58 95]
 [88 91 95 99 99]]


In [7]:
print('minimum-' , m.min() ,'and maximum - ' , m.max())  #here m is matrix , matrix.minimum , matrix. maximum

minimum- 9 and maximum -  99


# NUmpy conditions:

In [8]:
#below are employee salary
emp_sal = ri(8,70,10)
emp_sal

array([29, 55, 42, 17, 27, 10, 25, 16, 44, 30])

In [11]:
#if you want to find the salary which are less than or greater than some salary use np.where
#np.where gives index details
print(np.where(emp_sal <25)) #it will pick corresponding index number for example here numbers @index 3,5,7 are less than 25

(array([3, 5, 7], dtype=int64),)


In [13]:
#to fetch the corresponding data (only number not index)
emp_sal[np.where(emp_sal<25)]
#from data emp_sal check data @ index 3,5,7

array([17, 10, 16])

In [14]:
#set minimum and maximum salary using a_min and a_max
np.clip(emp_sal, a_min = 20 , a_max = 50)
#by using this method we can set salary of employees in b/w any limit
#all the number less than 20 and more than 50 will be replaced by another number b/w 20 to 50

array([29, 50, 42, 20, 27, 20, 25, 20, 44, 30])

# indexing and slicing:

In [15]:
arr = np.arange(13,30)

print("array-" , arr)

array- [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [16]:
print("element at 7th index is - " , arr[7])  

element at 7th index is -  20


In [17]:
print("elements at 2nd 4th and 7th index are -" , arr[[2,4,7]]) # if we are fething more than one index then we need to keep it in list
#above arr[7] , here we are fetching for more than 1 so arr[[2,4,7]] here 2,4,7 are in the list

elements at 2nd 4th and 9th index are - [15 17 20]


In [18]:
#how to fetch data from matrix
my_mat = ([1,2,3] , [4,5,6],[7,8,9])

mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# row wise index (0,1,2) and column wise index is (0,1,2)

In [20]:
print("\ndouble bracket indexing----------------------------------")
print("elements in row index 1 and column index 2: " , mat[1][2])


double bracket indexing----------------------------------
elements in row index 1 and column index 2:  6


In [21]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
mat[2][0]

7

In [24]:
mat[2][2]

9

In [26]:
print("entire row at index 2 :" , mat[2]) #this will fetch row at index  2
print("\nentire column at index: \n" , mat[:,1:]) # : means no starting no ending 
#look at [:,1:]
# with row wise space:space = everything which is [:] this part before the comma 
#and with column wise = 1: which means fetch 1st column and till ending column which is column 2 here

entire row at index 2 : [7 8 9]

entire column at index: 
 [[2 3]
 [5 6]
 [8 9]]


In [27]:
print("\nSubsetting sub matrices \n------------------------------------")
print("matrix with row indices 1 and 2 and column indices 3 and 4 \n", mat[1:2,1:2])


Subsetting sub matrices 
------------------------------------
matrix with row indices 1 and 2 and column indices 3 and 4 
 [[5]]


In [28]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print("" , mat [0:2,[1,2]]) #row side we are using 0:2 and column side we are using 1,2

 [[2 3]
 [5 6]]


In [33]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# update matrix:

In [34]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
mat[2][2] = 7 #updating 9 to 7 in the matrix mat

In [36]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 7]])

In [37]:
print('original matrix\n\n' ,mat)

original matrix

 [[1 2 3]
 [4 5 6]
 [7 8 7]]


In [38]:
mat[0][1] = 23

In [39]:
mat

array([[ 1, 23,  3],
       [ 4,  5,  6],
       [ 7,  8,  7]])

In [40]:
mat[0][2] = 26

In [41]:
mat

array([[ 1, 23, 26],
       [ 4,  5,  6],
       [ 7,  8,  7]])

In [42]:
mat[1][0] = 100
print(mat)

[[  1  23  26]
 [100   5   6]
 [  7   8   7]]


# subsetting:

In [43]:
mat = np.array(ri(10,100,15)).reshape(3,5)

print("matrix of random two digit number is \n----------------------------\n" , mat)

matrix of random two digit number is 
----------------------------
 [[72 85 48 29 98]
 [13 43 65 15 54]
 [62 42 26 72 62]]


In [44]:
mat>50 # it is like a question

array([[ True,  True, False, False,  True],
       [False, False,  True, False,  True],
       [ True, False, False,  True,  True]])

In [45]:
print("elements greater than 50\n" , mat[mat>50])

elements greater than 50
 [72 85 98 65 54 62 72 62]


In [46]:
#we can also use where and write some condition to fetch the data
marks = 50
np.where(marks>68 ,'pass', 'fail' )

array('fail', dtype='<U4')

In [47]:
 marks = 70
np.where(marks>68 ,'pass', 'fail' )

array('pass', dtype='<U4')

In [48]:
# check non zero
non_zero = ri(-10,50,100)

print(non_zero)

np.count_nonzero(non_zero)   #here all 100 elements are non zero

[ 46  -7  -1  33  32  35  23  11  44  -4  15  -1  -4  15  27  16  26  44
  -5  41  15  14  49  37  32  16  14  27  10  -7  27  48  24   7  14  -4
  27  30  -8  30   6  -6  17  15  10  18  13  26  35  38  32  42  -7   6
  20  13  28  36  48  23  15  33  15  -2  45  48  34  10  25   5  11  33
  -8  41  43  12  28  36  -4  18   6  -5  17  30  29  13   5  14  20  40
  25 -10  32  47  46  19  32  20  45  23]


100

In [49]:
non_zero = ri(-10,50,100)

print(non_zero)

np.count_nonzero(non_zero) #here in output nonzero are 97 and 3 are zero 

[  1  -4   6  22  22  39  41  10  14  43  -1  -1  -7  31  41   3  17   6
  49  37   0  -8  18  13  48  -6  10  -2  34  -9  15  27   7   8  11   4
  23  15  10   0  26  47  11   0  38   1   1  11  33  35  37  47  -3  40
  -4  42  33  33  22  43  37  42  30   7  -8  24   1   2  38   3  10  37
  39  -8  32  16  16  -5  -9  21  44  37  13  -4  -5  44  46  35   7  49
  36  14  -7   7   7  -2  31  36  -4 -10]


97

In [50]:
# ravel or flatten(this concept is used in deep learning for image processing)
array = np.random.randint(0,20 , size = (3,4))

print(array)

array.ravel()

[[ 2  2 13 10]
 [ 7  0 17  7]
 [ 1 19 14  2]]


array([ 2,  2, 13, 10,  7,  0, 17,  7,  1, 19, 14,  2])

In [51]:
# or flatten both are same 
array.flatten()

array([ 2,  2, 13, 10,  7,  0, 17,  7,  1, 19, 14,  2])

# universal function:

In [53]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

print("\n1st matrix of single digit number \n---------------------------\n" , mat1)

print("\n2nd matrix of single digit number \n----------------------------\n" , mat2)


1st matrix of single digit number 
---------------------------
 [[2 1 3]
 [4 7 2]
 [1 8 4]]

2nd matrix of single digit number 
----------------------------
 [[8 5 6]
 [3 5 3]
 [8 7 1]]


In [54]:
print("\n addition\n---------------------------\n" , mat1+mat2)


 addition
---------------------------
 [[10  6  9]
 [ 7 12  5]
 [ 9 15  5]]


In [55]:
print("\n subtraction\n-------------------------\n" , mat1 - mat2)


 subtraction
-------------------------
 [[-6 -4 -3]
 [ 1  2 -1]
 [-7  1  3]]


In [56]:
print("\n product\n-------------------------\n" , mat1*mat2)


 product
-------------------------
 [[16  5 18]
 [12 35  6]
 [ 8 56  4]]


# Broadcasting:

In [57]:
start = np.zeros((3,3))

In [58]:
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
# create a rank nd array with 3 values
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [60]:
y = start + add_rows #add to each row of start using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [61]:
# broadcasting is to add/subtract/divide/multiply different types of matrix that are not equal in size

In [95]:
 a = np.array([1,0,2]).T

In [96]:
a

array([1, 0, 2])

In [97]:
#  to know the function we use cursor inside the bracket and use shift+tab